### ISSUE TITLE
[Bug] `formatTSDeclarations'` does not honor `typeAlternativesFormat` if there is more than 1 `TSDeclaration` in the input list

### ISSUE THREAD

**Issue by sir4ur0n** [codedownio/aeson-typescript#41]
This is a weird bug that I noticed and took time to track down in our code base :smile: 

In essence, you can reproduce it by modifying a bit the inputs of the test `/Formatting/when given multiple Sum Types`.
E.g., https://github.com/codedownio/aeson-typescript/blob/master/test/Formatting.hs#L50

1. Add a new `D2` type, similar to `D`
```hs
data D = S | F deriving (Eq, Show)

$(deriveTypeScript defaultOptions ''D)

data D2 = S2 | F2 deriving (Eq, Show)

$(deriveTypeScript defaultOptions ''D2)
```

2. Add `D2` to the list of `TSDeclaration` used in the 3 unit tests: replace `(getTypeScriptDeclarations @D Proxy)` with `(getTypeScriptDeclarations @D Proxy <> getTypeScriptDeclarations @D2 Proxy)`

3. :boom: Notice that the generated Typescript code gets completely wrong

E.g., for test `should generate a TS Enum`, you would expect the output to be `enum D { S, F }\n\nenum D2 { S2, F2 }`, right?
Well it turns out the actual output becomes `type D = \"S\" | \"F\";\n\ntype D2 = \"S2\" | \"F2\";`, i.e. it behaves like `typeAlternativesFormat = TypeAlias`!

The same bug happens for `EnumWithType`.

**Comment by thomasjm** [comment]
Thanks for the report!

I've got a partial fix in a7d273e. There was some odd formatting code introduced in #20, which tries to detect if enum mode should be used based on how many constructors are present. As you discovered, doing this by looking over the full list passed to `formatTSDeclarations'` doesn't make sense.

I got rid of this function, but I'm concerned this breaks some behavior that used to work. For example, if you make a unit like `data Unit = U` and then try to format it with enum mode turned on, it will produce an invalid enum. Whereas the previous code would have automatically switched it over to a type alias.

I think doing this properly might be as simple as only enabling enum mode when all the type alternatives are double-quoted strings...

**Comment by thomasjm** [comment]
Okay, I think there's a better check now in 2e5c1234e770877ce62a18e23a8dc811ade25079. Want to try it?

**Comment by thomasjm** [comment]
I'm pretty sure that's not a valid enum. If I paste it into my editor, I get `Enum declarations can only merge with namespace or other enum declarations`. That seems to be an error TSC often gives for messed-up enums.

AFAICT enums need to contain symbol names, which can optionally be mapped to either strings or numbers; see [here](https://www.typescriptlang.org/docs/handbook/enums.html). So it makes sense for `aeson-typescript` to only output enums when all constructors encode like this.

**Comment by sir4ur0n** [comment]
I am totally confused by your last reply :sweat_smile: 

What is the relationship between "An enum has 1 or several values" and "The enum syntax is invalid"?
I just tested the following enums with only 1 constructor, both in my project, and in [Typescript REPL](https://www.typescriptlang.org/play?ssl=13&ssc=32&pln=1&pc=1#code/KYOwrgtgBAqiCWAXAjFA3gKCt2AaDAvhhqJLAogEwCi40mOUAylALxQBETH+RiAngAdg5JJTZQA1sH4B7AGZQBwhaKq1IAbmIBjWSADOsgDbAAdMdkBzABRwkyMzACUmqAHp3UAAoAneCCIBlAABgAMIRh6hibmlrb26nRmTK4eXn4BQaFcHJHRBohQAB5QAFxq4uy52gWxFtY2xWmePv6BwSG5IUA), and it works fine in both places:

```ts
enum Unit1 {
    U,
}

enum Unit2Enum {
    S = "S",
}
type Unit2 = keyof typeof Unit2Enum;

console.log(Unit1.U); // Prints `0`
console.log(Unit2Enum.S); // Prints `"S"`
const x : Unit2 = "S";
console.log(x); // Prints `"S"`
```

My point is that, even if the Haskell data type has a single constructor (e.g. `data Unit = U`), then the generated Typescript code should honor the `typeAlternativesFormat` parameter:
* `TypeAlias` -> `type Unit = "U"`
* `Enum` -> `enum Unit { U }`
* `EnumWithType` -> `enum UnitEnum { U = "U" } \n\ntype Unit = keyof typeof UnitEnum`

Not only is this more intuitive, but this also behaves better in the face of future changes.
E.g. adding a new constructor to `Unit` does not suddenly change the Typescript type definition from `void[]` to `enum`, and vice versa

**Comment by thomasjm** [comment]
Oh whoops, I misread your last message. Yes, `enum Unit { U }` makes sense as an enum. So do your proposals for the other values of `typeAlternativesFormat`.

> adding a new constructor to Unit does not suddenly change the Typescript type definition from void[] to enum, and vice versa

That's exactly what it does in `aeson`. A single constructor often encodes totally differently. When you take `data Unit = U` and derive JSON instances using `defaultOptions`, then `A.encode U` gives `"[]"`. We can't pretend this is an enum in the TypeScript types or else the types won't match the reality.

You can get a unit to encode as a string by doing `tagSingleConstructors = True` in your Aeson options. Then `A.encode U` gives `"U"`. However, even then it would be wrong to type this as `enum Unit { U }`, because as you say, `console.log(Unit1.U)` yields `0`. It seems we have to always specify the string: ``enum Unit { U="U" }`.

I just updated the formatting code to always put the string value in the enums and added some tests. I think it's good now?

**Comment by sir4ur0n** [comment]
Aaaaah I see. Yeah indeed, consistency with the Aeson instances makes sense.

Yeah, the current version on `master` looks good AFAICT :+1: 

Do you want to close the issue now, or once a new version is released?

**Comment by thomasjm** [comment]
Released:

https://github.com/codedownio/aeson-typescript/tree/v0.6.1.0

https://hackage.haskell.org/package/aeson-typescript-0.6.1.0
